name: Update Main from Staging

on:
  schedule:
    - cron: '* * * * */3'  # Ejecutar cada 5 minutos

jobs:
  update-main:
    name: Update Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set Git identity
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"


      - name: Merge from Staging
        run: |
          git fetch origin
          git merge origin/staging  --no-edit
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Deploy to Production on Railway
        run: |
          npm i -g @railway/cli
          railway up --service pruebaintegracionC
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PRODUCTION }}