name: Deploy Docker on Railway

on:
  pull_request:
    branches:
      - staging
      
jobs:
  Deploy_desde_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Ingresar a mi cuenta docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Imagen de docker
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/dracosnape-app:latest

      - name: Instalacion de railway
        run: npm i -g @railway/cli
          
      - name: Deploy a Railway
        run: railway up --service deploydocker
        env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_DOCKER_PRODUCTION }}