name: Deploy en railway utilizando un imagen de docker
on:
  pull_request:
    branches:
      - staging
      
jobs:
  Deploy_desde_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Ingresar a mi cuenta docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and  Push Docker image
        uses: docker/build-push-action@v3
        with:
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/dracosnape-app:latest

      - name: Pull Docker image
        run: docker pull ${{secrets.DOCKER_USERNAME}}/dracosnape-app:latest
            
#          - name: Install Railway # 1
#            run: npm i -g @railway/cli
#          
#          - name: Deploy 
#            run: railway up --service deploydocker
#            env:
#                RAILWAY_TOKEN: ${{ secrets.RAILWAY_DOCKER_PRODUCTION }} 
