name: Deploy on Railway using Github repository

on:
  pull_request:
    branches:
    - staging
   
      
jobs:
  Deploy_desde_github:

    runs-on: ubuntu-latest

    env:
      MONGO: ${{ secrets.MONGO_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      RAILWAY_DOCKER_PRODUCTION: ${{ secrets.RAILWAY_DOCKER_PRODUCTION }}

    steps:

    - name : Git checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Usar version de node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Construir projecto
      run: npm run build --if-present

    - name: Correr los test
      run: npm test

    - name: Verificar cambios en la rama staging
      run: |
        git checkout main
        git pull origin main
        git checkout staging
        git merge --no-commit --no-ff main
        git diff --name-only --diff-filter=U
    

  sonarcloud:
      runs-on: ubuntu-latest
      needs: Deploy_desde_github
      if: success() 

      env:
        MONGO: ${{ secrets.MONGO_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}

      steps:
      - name : Git checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Instalar dependencias
        run: npm ci
  
      - name: Testeo y cobertura
        run: npm test --coverage


      - name: scanear SonarCloud 
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
          MONGO: ${{ secrets.MONGO_URL }}

  


    