name: Deploy on Railway using Github repository

on:
  pull_request:
    branches:
      staging
   
      
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MONGO: ${{ secrets.MONGO_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      RAILWAY_DOCKER_PRODUCTION: ${{ secrets.RAILWAY_DOCKER_PRODUCTION }}

    steps:

    - name : Git checkout 
      uses: actions/checkout@v4

    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies 
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Run test
      run: npm test
    
    
    #- name: SonarQube Scan
    #  uses: sonarsource/sonarqube-scan-action@v2
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}


    