name: CI Workflow

on:
  push:
    branches: [ "staging", "main" ]
   

      
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    env:
      MONGO: ${{ secrets.MONGO_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      RAILWAY_DOCKER_PRODUCTION: ${{ secrets.RAILWAY_TOKEN }}

    steps:

    - name : Git checkout 
      uses: actions/checkout@v4

    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies 
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Run test
      run: npm test
    
    
    #- name: SonarQube Scan
    #  uses: sonarsource/sonarqube-scan-action@v2
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}


    - name: Log in to docker hub 
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
      
    - name: build and  Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/dracosnape-app:latest
      
    - name: Install Railway # 1
      run: npm i -g @railway/cli
          
    - name: Deploy to Railway
      run: |
          echo ${{ secrets.RAILWAY_DOCKER_PRODUCTION }} | railway login --token
          railway project deploy --from 'docker://${{ secrets.DOCKER_USERNAME }}/dracosnape-app:latest'