name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Install Railway CLI
            run: |
              apt-get update && apt-get install -y curl
              curl -fsSL https://railway.app/install.sh | sh
    
          - name: Login to Railway
            env:
              RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
            run: railway login --token "${RAILWAY_TOKEN}"
    
          - name: Deploy to Railway
            run: railway up