name: Notify Slack on Release

on:
  release:
    types:
       - created


jobs:
  notificar_slack:
    runs-on: ubuntu-latest


    name: Notificar en slack la nueva release
    steps:
      - name: Notify Slack on Release
        uses: tryfabric/notify-slack-on-release@1.0.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    
          