name: Actualizar main desde staging

on:
  workflow_dispatch

jobs:
  Subir_repositorio_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config --global user.email "leandro@gmail.com"
        git config --global user.name "Leandro tombetta"

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout staging
      run: git checkout staging

    - name: Update staging from remote
      run: git pull origin staging

    - name: Merge staging into main
      run: |
          git checkout main
          git merge staging -X theirs || echo "Conflictos detectados, revise manualmente."
          
    - name: Push changes to main
      run: git push origin main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
