name: Notificar que la actualizacion a main ha sido correcto

on:
  workflow_run:
    workflows: ["Actualizar main desde staging"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: notificar por slack
      uses: rtCamp/action-slack-notify@v2
      with:
        text: "GitHub Actions workflow completed with status: ${{ job.status }}"
        username: '"Actualizar main desde staging'
        icon_emoji: ':rocket:'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}