name: Notificar que la actualizacion a main ha sido correcto

on:
  workflow_run:
    workflows: ["Actualizar main desde staging"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar por slack
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL}}
          status: ${{ job.status }}
          text: "GitHub Actions workflow completed successfully!"
          username: 'GitHub Actions'
          icon_emoji: ':rocket:'