name: Notificar que la actualizacion a main ha sido correcto

on:
  workflow_run:
    workflows: ["Actualizar main desde staging"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
    - uses: ravsamhq/notify-slack-action@v2
      with:
        status: success
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}